conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from item.models import Category, Item

from .forms import SignupForm

def index(request):
    """
    Главная страница: отображает последние 6 непроданных товаров и все категории
    """
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    """
    Страница контактов: просто отображает контактную информацию
    """
    return render(request, 'core/contact.html')


def signup(request):
    """
    Страница регистрации: позволяет новому пользователю зарегистрироваться
    """
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def logout_user(request):
    """
    Функция выхода пользователя из системы
    """
    if request.method == 'POST':
        logout(request)
        return redirect("/")
    return render(request, 'core/logout.html')

core/templates/core/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %} | MUSICAL COLLEGE</title>
  </head>

  <body>
    <nav
      class="py-6 px-6 flex justify-between items-center border-b border-gray-200"
    >
      <a href="/" class="text-xl font-semibold">MUSICAL COLLEGE</a>

      <div class="space-x-6">
        {% if user.is_authenticated and user.username == 'kenes' %}
        <a
          href="{% url 'item:new' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >Новый инструмент</a
        >
        {% endif %}
        <a
          href="{% url 'item:items' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >Все инструменты</a
        >

        {% if request.user.is_authenticated %}
        <a
          href="{% url 'conversation:inbox' %}"
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
          >Входящие</a
        >
        {% if user.is_authenticated and user.username == 'kenes' %}
        <a
          href="{% url 'dashboard:index' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
          >Приборная панель</a
        >
        {% endif %}
        <a
          href="{% url 'core:logout' %}"
          class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"
          >Выйти</a
        >

        {% else %}
        <a
          href="{% url 'core:signup' %}"
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
          >Зарегистрироваться</a
        >
        <a
          href="{% url 'core:login' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
          >Войти</a
        >

        {% endif %}
      </div>
    </nav>

    <div class="px-6 py-6">{% block content %} {% endblock %}</div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">О нас</h3>

        <p class="text-lg text-gray-500">
          Наш музыкальный Комплекс это уникальное элитное учебное заведение
          Павлодарской области. Несмотря на свой солидный возраст (в 2024 году
          колледжу исполнилось 65 лет) оно имеет юное и очень привлекательное
          лицо, потому что люди, занимающиеся искусством, умеющие создавать
          прекрасное, способны сохранять вечную молодость.
        </p>
      </div>

      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Меню</h3>

        <ul class="space-y-2">
        
          <li>
            <a
              href="https://www.instagram.com/muz_coll_pvl/"
              class="text-lg text-teal-500 hover:text-teal-700"
              >Контакты</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700"
              >Политика конфиденциальности</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700"
              >Условия использования</a
            >
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %} {% block title %}Добро пожаловать{% endblock %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Новые инструменты</h2>

  <div class="grid grid-cols-3 gap-6">
    
    {% for item in items|slice:":3" %}
    <div class="relative overflow-hidden rounded-xl shadow-md bg-white">
      <a href="{% url 'item:detail' item.id %}" class="block">
        <img
          src="{{ item.image.url }}"
          alt="{{ item.name }}"
          class="w-full h-64 object-cover rounded-t-xl"
        />
        <div class="p-4 bg-white rounded-b-xl">
          <h2 class="text-xl font-semibold mb-2">{{ item.name }}</h2>
          <p class="text-gray-700">В наличии: {{ item.in_stock }}</p>
        </div>
      </a>
    </div>

    {% endfor %}
</div>

</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Категории</h2>

  <div class="grid grid-cols-3 gap-3">
    {% for category in categories %}
    <div>

        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">


        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="text-2xl">{{ category.name }}</h2>
          <p class="text-gray-500">{{ category.items.count }} инструментов </p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Войти{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Войти</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Имя пользователя</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Пароль</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/logout.html
{% extends 'core/base.html' %} {% block title %}Выйти{% endblock %} 
{% block content %}
<style>
    .container {
        display: flex;
        justify-content: space-around;
    }
</style>
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl container">
  {% if user.is_authenticated %}
  <form method="post" action="">
    {% csrf_token %}
    <button
      class="py-3 px-8 text-lg bg-red-500 hover:bg-red-500 rounded-xl text-white"
    >
      Выйти
    </button>
    <a href="/" class="py-3 px-8 text-lg bg-teal-500 rounded-xl text-white">Отмена</a>
  </form>

  {% else %}
  <p>Вы не авторизованы.</p>
  {% endif %}
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Зарегистрироваться{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Зарегистрироваться</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Имя пользователя</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Пароль</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Повторите пароль</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}